"""initial schema

Revision ID: 76888bd3ee87
Revises: 
Create Date: 2026-09-28 11:50:40.722877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76888bd3ee87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_user_problem_submitted', ['user_id', 'problem_id', 'submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_user_problem_submitted')

    # ### end Alembic commands ###
